@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Receptionist" as NRS
participant "SelectVaccinationCenterUI" as UI
participant "SelectVaccinationCenterController" as CTRL
participant ":App" as APP
participant "plat\n : Platform" as PLAT
participant "app:App" as App
participant "comp\n:Company" as Comp
participant "rvc\n:RegisterVaccinationCenter" as RVC
participant "reg\n:RegisterEmployee" as RE
participant "emp\n :Employee" as EMP
participant "session \n:UserSession" as SESSION
participant "email\n :Email" as EMAIL
participant "emp\n :Employee" as EMP
participant "lst\n: List<VaccinationCenter>" as LVC
participant "vac\n:VaccinationCenter" as VC
participant "vaccinationCenter\n:Object"
participant "le\n :List<Employee>"

activate NRS

NRS -> UI : Selecting the vaccination center where s(he) works
activate UI

UI -> CTRL : create

activate CTRL
CTRL -> APP : app = getInstance()
activate APP
deactivate APP
'4
CTRL -> App : comp = getCompany()
activate App
deactivate App
'5
CTRL -> Comp : plat = getPlatform()
activate Comp
deactivate Comp
deactivate CTRL



UI -> CTRL : lst = getListVaccinationCenter()
activate CTRL
CTRL -> PLAT : rvc = getRegisterVaccinationCenter()
activate PLAT
deactivate PLAT
CTRL -> RVC :  getListVaccinationCenters()
activate RVC
deactivate CTRL
deactivate RVC

UI --> NRS : show list of vaccination centers and ask to select one
deactivate UI
NRS -> UI : selects the intended vaccination center
activate UI

'9
UI -> CTRL :setWorkingVaccinationCenter(vac)
activate CTRL
'10
CTRL -> PLAT : reg = getRegisterEmployee()
activate PLAT
deactivate PLAT
'11
CTRL -> App : email = getCurrentUserSession()
activate App
'12
App -> SESSION : getUserId()
activate SESSION
'13
SESSION -> EMAIL : getEmail()
activate EMAIL
deactivate EMAIL
deactivate SESSION
deactivate App

CTRL -> RE : emp = getEmployeeByEmail(email)
activate RE
deactivate RE

CTRL -> EMP : setWorkingVaccinationCenter(vac)
activate EMP
deactivate EMP


deactivate NRS


@enduml