@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "App" as APP
participant ":Company" as COMP
participant ":Platform" as PLAT
participant "auth:AuthFacade" as AF
participant "registerSNSUser\n:RegisterSNSUser" as RE
participant ":LoadUsersFromCSV" as LFC


activate APP
APP --> COMP** : create(designation)
activate COMP
COMP --> AF ** : create()
COMP --> PLAT **: create(designation)
deactivate COMP
APP -> APP ++: bootstrap()
APP -> PLAT: initializeRegisters(auth)

activate PLAT
PLAT --> RE **: create(auth)
PLAT --> LFC **: create(auth,registerSNSUser)
deactivate PLAT
deactivate APP
@enduml