@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ":RegisterSNSUser" as RE
participant "<<interface>>\n alg: PasswordGenerator" as PG
participant ":PasswordsGeneratorRandomly" as PGR
participant "<<interface>>\n:SendEmail" as SE

activate RE
RE -> PG :  passwordGenerator()
activate PG
PG --> PGR **: create()
activate PGR
PGR -> PGR : pwd = passwordGenerator(email)
PGR -> SE : SendEmail()
activate SE
deactivate SE
note over RE: During Sprint C, the need to generate \nrandom passwords come up with US14.\nAs such, to avoid code duplication, by PureFabrication\n,such responsibility must be assigned to a specific class\n specialized in that task.Nested class declared within interface body,\n and this nested class implements outer interface.
PG --> RE :pwd
deactivate PGR
deactivate PG

deactivate RE


@enduml